# Generated by Django 5.1.1 on 2024-12-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_astrobit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecarddata',
            name='game_title',
            field=models.CharField(max_length=25),
        ),
    ]
