# Generated by Django 5.1.1 on 2024-12-11 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_astrobit', '0002_alter_gamecarddata_game_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(db_column='name', max_length=255),
        ),
        migrations.AlterField(
            model_name='gamecarddata',
            name='author_name',
            field=models.ForeignKey(db_column='author_id', on_delete=django.db.models.deletion.CASCADE, related_name='gamecards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rankuser',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to=settings.AUTH_USER_MODEL),
        ),
    ]
