# Generated by Django 5.1.1 on 2024-12-10 20:52

import api_astrobit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_astrobit', '0003_rename_author_gamecarddata_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecarddata',
            name='game_image_url',
            field=models.URLField(blank=True, default='https://raw.githubusercontent.com/alef-monteiro/astrobit-front/refs/heads/develop/src/assets/illustration-game-card.png', help_text='Insira o link de uma imagem para o gamecard.', max_length=500, null=True, validators=[api_astrobit.models.validate_image_url], verbose_name='Gamecard Image URL'),
        ),
        migrations.AlterField(
            model_name='gamecarddata',
            name='game_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gamecarddata',
            name='username',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='rankuser',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[api_astrobit.models.validate_image_url]),
        ),
    ]
